version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.6
      - image: devopsdunkin/nagiosxi:ci-tests

    working_directory: /go/src/github.com/devopsdunkin/gonagios
    steps:
      - checkout
      - run: go mod download
      - save_cache:
          key: go-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          command: |
            go test -v
    environment:
      GO111MODULE: "on"

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/