version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.6
      - image: devopsdunkin/nagiosxi:ci-tests

    working_directory: /go/src/github.com/devopsdunkin/gonagios
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...